### ISSUE TITLE
Multi-domain / Sub-domains?

### ISSUE THREAD

**Issue by xpbliss** [goaltools/goal#42]
In httprouter, it supportes ```Multi-domain / Sub-domains```?
https://github.com/julienschmidt/httprouter#web-frameworks-based-on-httprouter
Could goal support it?

**Comment by alkchr** [comment]
1. Goal can work with any router.
2. Default router is [`denco`](https://github.com/naoina/denco). Or rather a wrapper around it for better integration with Goal and smoother user experience. It doesn't handle domains, [URN](https://en.wikipedia.org/wiki/Uniform_Resource_Name#/media/File:URI_Euler_Diagram_no_lone_URIs.svg) only.
3. Routes generation doesn't have anything related to domains either.

Both our router wrapper and routes generation tool can be modified to support this functionality. I just need to understand the use-case for this.

1. Is it a mechanism for listening on different hosts/ports?
2. Or is a way of using different routes for different hosts/ports?

**Comment by xpbliss** [comment]
Using different routes for different hosts/ports.

**Comment by xpbliss** [comment]
Have you new update for the goal?

**Comment by xpbliss** [comment]
How about your new progress on the goal?
